[package]
name = "rfm12b"
version = "0.1.0"
authors = ["Leon Tan <leon.arian.tan@gmail.com>"]

[dependencies.register]
path = "../register"

[dependencies.embedded-hal]
version = "^0.1.2"
features = ["unproven"]

[dependencies.byteorder]
default-features = false
version = "^1.2.1"